# Generated by Django 5.1.1 on 2024-09-11 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vol_per_block', models.FloatField()),
                ('width', models.FloatField()),
                ('height', models.FloatField()),
                ('depth', models.FloatField()),
                ('face_area', models.FloatField()),
                ('image', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company_name', models.IntegerField(blank=True, null=True)),
                ('concrete_density', models.FloatField(blank=True, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=255, null=True)),
                ('concrete_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('labour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_truck_capacity', models.FloatField(blank=True, null=True)),
                ('infill_density', models.FloatField(blank=True, null=True)),
                ('infill_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_truck_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('avg_production_time', models.FloatField(blank=True, null=True)),
                ('royalty', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pur_per_year', models.FloatField(blank=True, null=True)),
                ('cem_content', models.FloatField(blank=True, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=255, null=True)),
                ('language', models.CharField(blank=True, default='en', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('face_area', models.FloatField(blank=True, null=True)),
                ('labour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('concrete', models.FloatField(blank=True, null=True)),
                ('concrete_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('infill', models.FloatField(blank=True, null=True)),
                ('infill_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('delivery_weight', models.FloatField(blank=True, null=True)),
                ('delivery_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('co2_emissions', models.FloatField(blank=True, null=True)),
                ('royalties', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='projects.project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SectionBlock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField()),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.block')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.section')),
            ],
        ),
    ]
