# Generated by Django 5.1.1 on 2024-09-11 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
