# Generated by Django 5.1.1 on 2024-09-11 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_project_contact_alter_section_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
