# Generated by Django 5.1.1 on 2024-10-14 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_block_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='block',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='project',
            name='cem_content',
            field=models.FloatField(blank=True, default=0.16, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='concrete_density',
            field=models.FloatField(default=2350),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='project',
            name='royalty',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
