# Generated by Django 5.1.1 on 2024-10-14 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_remove_block_created_at_remove_block_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='concrete',
            new_name='concrete_volume',
        ),
    ]
